### ISSUE TITLE
Fastq.gz not parsing appropriately

### ISSUE THREAD

**Issue by hextraza** [BimberLab/nimble#62]
The bam workflow gets run when you pass --input R1.fastq.gz --input R2.fastq.gz instead of fastq::align

**Comment by derrik-gratz** [comment]
```
podman run -v /yerkes-cifs:/yerkes-cifs -ti ghcr.io/bimberlab/nimble align \
--reference /yerkes-cifs/runs/Analysis/2023_Analyses/p23120_Amanda/Data/mmul10_missing_features.json \
--output /yerkes-cifs/runs/Analysis/2023_Analyses/p23120_Amanda/Processing/nimble/nimble_test.tsv \
--input /yerkes-cifs/runs/Analysis/2023_Analyses/p23120_Amanda/Data/p23120_Amanda-230608A/p23120-s001_Capture-39-5-GEX-LIB_S1_L001_R1_001.fastq \
--input /yerkes-cifs/runs/Analysis/2023_Analyses/p23120_Amanda/Data/p23120_Amanda-230608A/p23120-s001_Capture-39-5-GEX-LIB_S1_L001_R2_001.fastq
```

**Comment by derrik-gratz** [comment]
I'll throw this in here too, in case you are interested in allowing the wildcard expansion for the input field, you can specify `nargs` too an argparse argument to allow multiple entries 

https://docs.python.org/3/library/argparse.html#nargs

**Comment by derrik-gratz** [comment]
Also, the non-parsing issue for fastq inputs happens with both `.fastq` and `.fastq.gz` extensions

**Comment by hextraza** [comment]
> ```
> podman run -v /yerkes-cifs:/yerkes-cifs -ti ghcr.io/bimberlab/nimble align \
> --reference /yerkes-cifs/runs/Analysis/2023_Analyses/p23120_Amanda/Data/mmul10_missing_features.json \
> --output /yerkes-cifs/runs/Analysis/2023_Analyses/p23120_Amanda/Processing/nimble/nimble_test.tsv \
> --input /yerkes-cifs/runs/Analysis/2023_Analyses/p23120_Amanda/Data/p23120_Amanda-230608A/p23120-s001_Capture-39-5-GEX-LIB_S1_L001_R1_001.fastq \
> --input /yerkes-cifs/runs/Analysis/2023_Analyses/p23120_Amanda/Data/p23120_Amanda-230608A/p23120-s001_Capture-39-5-GEX-LIB_S1_L001_R2_001.fastq
> ```
> 
> ```
> Aligning input .bam to the reference libraries
> ['--input', '/yerkes-cifs/runs/Analysis/2023_Analyses/p23120_Amanda/Data/p23120_Amanda-230608A/p23120-s001_Capture-39-5-GEX-LIB_S1_L001_R2_001.fastq', '-c', '1', '--strand_filter', 'unstranded', '-r', '/yerkes-cifs/runs/Analysis/2023_Analyses/p23120_Amanda/Data/mmul10_missing_features.json', '-o', '/yerkes-cifs/runs/Analysis/2023_Analyses/p23120_Amanda/Processing/nimble/nimble_test.tsv']
> Loading and preprocessing reference data for /yerkes-cifs/runs/Analysis/2023_Analyses/p23120_Amanda/Data/mmul10_missing_features.json
> Total 156227 kmers to process in dbg
> Making mphf of kmers
> Assigning offsets to kmers
> Total 156227 kmers to process in dbg
> Making mphf of kmers
> Assigning offsets to kmers
> Loading read sequences and aligning
> Spawning consumer thread 0
> Spawning reader thread.
> Spawning logging thread.
> thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: BamOpen { target: "/yerkes-cifs/runs/Analysis/2023_Analyses/p23120_Amanda/Data/p23120_Amanda-230608A/p23120-s001_Capture-39-5-GEX-LIB_S1_L001_R2_001.fastq" }', src/parse/sorted_bam_reader.rs:14:50
> note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
> thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Any { .. }', src/process/bam.rs:181:28
> ```

Most recent release should fix this workflow, allowing multiple files to be passed to --input
